version: '3.4'

services:
  books:
    build:
      context: .
      dockerfile: Books/Dockerfile
    container_name: book-histoy
    ports:
      - "55667:80"

  sqlServerBooksDb:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "DiLb984ImW"
        ACCEPT_EULA: "Y"
    ports:
      - "1560:1433" 
    container_name: SqlServerDocker-BooksApp
    volumes:
      - "./db-data:/var/opt/mssql/data"

volumes:
  db-data: